### ISSUE TITLE
The file 'pymobiledevice3' doesnt exist

### ISSUE THREAD

**Issue by cowpatch** [nexron171/SimVirtualLocation#10]
Hi! I have downloaded pymobiledevice 3 and successfully installed the module but in the app I see the error that the file does not exist. What am I missing? And what are the steps to use the location changer (: thanks!

<img width="259" alt="Screenshot 2024-01-10 at 10 30 25 AM" src="https://github.com/nexron171/SimVirtualLocation/assets/156235069/dc655364-1692-4539-b8ee-7937debbb0f6">

**Comment by ieaksu** [comment]
It might be on a related note. I just received this error today.
<img width="289" alt="Screenshot 2024-01-10 at 3 07 32 PM" src="https://github.com/nexron171/SimVirtualLocation/assets/154739221/55149e3f-a072-4df8-b772-2ee8bfd9c84f">

**Comment by nexron171** [comment]
> It might be on a related note. I just received this error today. <img alt="Screenshot 2024-01-10 at 3 07 32 PM" width="289" src="https://private-user-images.githubusercontent.com/154739221/295698140-55149e3f-a072-4df8-b772-2ee8bfd9c84f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTkwODQsIm5iZiI6MTcwNjM1ODc4NCwicGF0aCI6Ii8xNTQ3MzkyMjEvMjk1Njk4MTQwLTU1MTQ5ZTNmLWEwNzItNGRmOC1iNzcyLTJlZThiZmQ5Yzg0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMjMzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjkyNmFmYTBlMzFkMDExMDU0YTNkNTI3MzY1MTliZGFhMDMxMmYyOTMxYjU1OTNiODliZGMxZjM3NzBhOTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sggt2_HyGEFw6Ij2w0tJzIKsDcF6aipP6syOlENn3L0">

Hi! @styresdc fixed it and fix is available in 3.3 https://github.com/nexron171/SimVirtualLocation/releases/tag/3.3

**Comment by nexron171** [comment]
> Hi! I have downloaded pymobiledevice 3 and successfully installed the module but in the app I see the error that the file does not exist. What am I missing? And what are the steps to use the location changer (: thanks!
> 
> <img alt="Screenshot 2024-01-10 at 10 30 25 AM" width="259" src="https://private-user-images.githubusercontent.com/156235069/295669649-dc655364-1692-4539-b8ee-7937debbb0f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTkxMDMsIm5iZiI6MTcwNjM1ODgwMywicGF0aCI6Ii8xNTYyMzUwNjkvMjk1NjY5NjQ5LWRjNjU1MzY0LTE2OTItNDUzOS1iOGVlLTc5MzdkZWJiYjBmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMjMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDFmOTgwZmFjYTMzY2ZkYzY1YjJlZjZhNTQ0ODNkZGQ2YWQxODQyNjFkOWNhMjMwMThiNWJmMzllZjI2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M_XtnOnFGzaTgE9mzgACiZk3z2n2J9uV_cH_jXyhZoc">

Hi, pymobile

> Hi! I have downloaded pymobiledevice 3 and successfully installed the module but in the app I see the error that the file does not exist. What am I missing? And what are the steps to use the location changer (: thanks!
> 
> <img alt="Screenshot 2024-01-10 at 10 30 25 AM" width="259" src="https://private-user-images.githubusercontent.com/156235069/295669649-dc655364-1692-4539-b8ee-7937debbb0f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTkxMDMsIm5iZiI6MTcwNjM1ODgwMywicGF0aCI6Ii8xNTYyMzUwNjkvMjk1NjY5NjQ5LWRjNjU1MzY0LTE2OTItNDUzOS1iOGVlLTc5MzdkZWJiYjBmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxMjMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDFmOTgwZmFjYTMzY2ZkYzY1YjJlZjZhNTQ0ODNkZGQ2YWQxODQyNjFkOWNhMjMwMThiNWJmMzllZjI2ZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M_XtnOnFGzaTgE9mzgACiZk3z2n2J9uV_cH_jXyhZoc">

Hi, please check that you have pymobiledevice3 linked to:
- on Apple Silicon here /opt/homebrew/bin/pymobiledevice3
- on Intel here /usr/local/bin/pymobiledevice3
