### ISSUE TITLE
Negative coordinate reads as option in 3.2

### ISSUE THREAD

**Issue by jasonhibbs** [nexron171/SimVirtualLocation#11]
Using 3.2 which I believe is updated to handle negative coordinates, seems to throw an error about my negative coordinates.

<img width="396" alt="Screenshot 2024-01-26 at 12 34 30" src="https://github.com/nexron171/SimVirtualLocation/assets/919628/b29236e3-2b6c-49db-993c-17d4769cb747">

<img width="1212" alt="Screenshot 2024-01-26 at 12 34 09" src="https://github.com/nexron171/SimVirtualLocation/assets/919628/1d3f45ab-0ee0-4be9-be30-a9cc4a6c7b49">

**Comment by nexron171** [comment]
Hi! @styresdc fixed it and fix is available in 3.3 https://github.com/nexron171/SimVirtualLocation/releases/tag/3.3
