### ISSUE TITLE
Add the İOS device

### ISSUE THREAD

**Issue by lalematoglu** [nexron171/SimVirtualLocation#12]
Hi. i downloaded the app and opened it on my mac what do i need to write in rsd address&port section? And how do I connect my ios device? And gives an error as I posted in the attachment. 
![Uploading Ekran Resmi 2024-03-27 18.07.18.png…]()

**Comment by nexron171** [comment]
Hi! You should open terminal and run `sudo python3 -m pymobiledevice3 remote start-tunnel`, it will write rsd address and port. Keep terminal runnig in background with this command and switch to SimVirtualLocation. Paste address and port in form. Now it should work.
