### ISSUE TITLE
Error: No such command 'developer'.

### ISSUE THREAD

**Issue by Leuchten** [nexron171/SimVirtualLocation#13]
Hello. i tried `python3 -m venv .venv && source .venv/bin/activate && sudo python3 -m pymobiledevice3 remote start-tunnel` for [this reason](https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana) to connect my iOS 17.4.1 device. 
Then i put RSD address/port. But error exists after i clicked 'Set A'(set location)
<img width="1212" alt="rds" src="https://github.com/nexron171/SimVirtualLocation/assets/9346892/dd27dc97-3746-41cb-ac9d-eb4a3bbf8faa">

**Comment by Leuchten** [comment]
iOS 17.1 -> iOS 17.4.1

**Comment by nexron171** [comment]
Hi! SimVirtualLocation does not support custom python environments :( 
I will check is it possible to make a custom command to run
