### ISSUE TITLE
Negative Location Values not allowed

### ISSUE THREAD

**Issue by AdzeB** [nexron171/SimVirtualLocation#15]
Using 3.3, but it seems to me that negative latitude is not allowed because I tried -- and - and it doesn't work

Can you please have a look

**Comment by nexron171** [comment]
Hi, please try new version 3.4 and check if problem gone

**Comment by AdzeB** [comment]
Hi, I will check it out today., Thanks

**Comment by AdzeB** [comment]
I tried and I am still getting an error.  
  
App version: 2.4.1

**Comment by nexron171** [comment]
> I tried and I am still getting an error.
> 
> App version: 2.4.1

could you please specify any address where I could reproduce an error

**Comment by AdzeB** [comment]
Formatted Address or Lat,Lang?

**Comment by nexron171** [comment]
> Formatted Address or Lat,Lang?

lat lon would be enough

**Comment by AdzeB** [comment]
Apologies for the delayed response, this is the lat lon: -26.144846,28.042191
