### ISSUE TITLE
crash once hit the set to A 

### ISSUE THREAD

**Issue by ghraibeh** [nexron171/SimVirtualLocation#18]
`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SimVirtualLocation [62891]
Path:                  /Applications/SimVirtualLocation.app/Contents/MacOS/SimVirtualLocation
Identifier:            com.devnex.SimVirtualLocation
Version:               3.5.1 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-10-09 17:36:24.9516 +0300
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        0AF4491E-DBDC-88A8-EADD-F14AE27B5455

Sleep/Wake UUID:       783E02B5-912A-47E1-AB2D-167796E5E5E8

Time Awake Since Boot: 1600000 seconds
Time Since Wake:       1085 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: executionQueue

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001b35df888

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [62891]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x190034ea4 __psynch_mutexwait + 8
1   libsystem_pthread.dylib       	       0x190070060 _pthread_mutex_firstfit_lock_wait + 84
2   libsystem_pthread.dylib       	       0x19006d9f0 _pthread_mutex_firstfit_lock_slow + 248
3   SwiftUI                       	       0x1bb9ea798 _MovableLockLock + 48
4   SwiftUI                       	       0x1bc74a048 0x1bb9e4000 + 14049352
5   SwiftUI                       	       0x1bc754f00 0x1bb9e4000 + 14094080
6   SwiftUI                       	       0x1bc7556d4 0x1bb9e4000 + 14096084
7   SwiftUI                       	       0x1bc758cf4 0x1bb9e4000 + 14109940
8   SwiftUI                       	       0x1bc957f7c 0x1bb9e4000 + 16203644
9   CoreFoundation                	       0x190152070 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
10  CoreFoundation                	       0x190151f84 __CFRunLoopDoBlocks + 356
11  CoreFoundation                	       0x190150db8 __CFRunLoopRun + 812
12  CoreFoundation                	       0x190150434 CFRunLoopRunSpecific + 608
13  HIToolbox                     	       0x19a8f419c RunCurrentEventLoopInMode + 292
14  HIToolbox                     	       0x19a8f3e2c ReceiveNextEventCommon + 220
15  HIToolbox                     	       0x19a8f3d30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
16  AppKit                        	       0x1939afd68 _DPSNextEvent + 660
17  AppKit                        	       0x1941a5808 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
18  AppKit                        	       0x1939a309c -[NSApplication run] + 476
19  AppKit                        	       0x19397a2e0 NSApplicationMain + 880
20  SwiftUI                       	       0x1bbaee474 0x1bb9e4000 + 1090676
21  SwiftUI                       	       0x1bc257e88 0x1bb9e4000 + 8863368
22  SwiftUI                       	       0x1bc652eb8 0x1bb9e4000 + 13037240
23  SimVirtualLocation            	       0x1049040a8 0x1048f0000 + 82088
24  dyld                          	       0x18fcea0e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x19006dd20 start_wqthread + 0

Thread 2:: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib        	       0x1900359ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19007355c _pthread_cond_wait + 1228
2   JavaScriptCore                	       0x1ad9ffbac scavenger_thread_main + 1316
3   libsystem_pthread.dylib       	       0x190072f94 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x19006dd34 thread_start + 8

Thread 3:: com.apple.coreanimation.render-server
0   libsystem_kernel.dylib        	       0x1900321f4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x190044b24 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19003ae34 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x190032578 mach_msg + 24
4   QuartzCore                    	       0x1983880ec CA::Render::Server::server_thread(void*) + 580
5   QuartzCore                    	       0x198387e98 thread_fun(void*) + 32
6   libsystem_pthread.dylib       	       0x190072f94 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x19006dd34 thread_start + 8

Thread 4 Crashed::  Dispatch queue: executionQueue
0   WebKit                        	       0x1b35df888 WTFCrashWithInfo(int, char const*, char const*, int) + 20
1   WebKit                        	       0x1b3bb37f4 WebKit::lockdownModeObservers() + 76
2   WebKit                        	       0x1b3bb3a10 WebKit::addLockdownModeObserver(WebKit::LockdownModeObserver&) + 56
3   WebKit                        	       0x1b3a7f6a8 -[WKWebpagePreferences init] + 152
4   WebKit                        	       0x1b3a7f590 +[WKWebpagePreferences defaultPreferences] + 16
5   WebKit                        	       0x1b3a7ab6c -[WKWebViewConfiguration defaultWebpagePreferences] + 40
6   WebKit                        	       0x1b3a7a4b4 -[WKWebViewConfiguration copyWithZone:] + 188
7   WebKit                        	       0x1b3a2aad4 -[WKWebView _initializeWithConfiguration:] + 128
8   WebKit                        	       0x1b3a2bb50 -[WKWebView initWithFrame:configuration:] + 72
9   WebKit                        	       0x1b3a2a9e4 -[WKWebView initWithFrame:] + 88
10  SimVirtualLocation            	       0x10491adc4 0x1048f0000 + 175556
11  SimVirtualLocation            	       0x10490dcd4 0x1048f0000 + 122068
12  SimVirtualLocation            	       0x10490bfa4 0x1048f0000 + 114596
13  SimVirtualLocation            	       0x10490bb8c 0x1048f0000 + 113548
14  SwiftUI                       	       0x1bc17f558 0x1bb9e4000 + 7976280
15  SwiftUI                       	       0x1bd103b70 0x1bb9e4000 + 24247152
16  SwiftUI                       	       0x1bd1036a4 0x1bb9e4000 + 24245924
17  SwiftUI                       	       0x1bbadd5b4 0x1bb9e4000 + 1021364
18  AttributeGraph                	       0x1bd6d35c0 AG::Graph::UpdateStack::update() + 512
19  AttributeGraph                	       0x1bd6d3dfc AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 424
20  AttributeGraph                	       0x1bd6e27ac AG::Subgraph::update(unsigned int) + 848
21  SwiftUI                       	       0x1bcfd4650 0x1bb9e4000 + 23004752
22  SwiftUI                       	       0x1bc956708 0x1bb9e4000 + 16197384
23  SwiftUI                       	       0x1bbc34328 0x1bb9e4000 + 2425640
24  SwiftUI                       	       0x1bbc34144 0x1bb9e4000 + 2425156
25  SwiftUI                       	       0x1bbc34ab0 0x1bb9e4000 + 2427568
26  SwiftUI                       	       0x1bd37d460 0x1bb9e4000 + 26842208
27  Combine                       	       0x1a22bd6f0 ObservableObjectPublisher.Inner.send() + 212
28  Combine                       	       0x1a22bcd94 ObservableObjectPublisher.send() + 652
29  Combine                       	       0x1a22a584c PublishedSubject.send(_:) + 144
30  Combine                       	       0x1a22d0820 static Published.subscript.setter + 432
31  Combine                       	       0x1a22d0ba4 static Published.subscript.modify + 208
32  SimVirtualLocation            	       0x1048f4fb4 0x1048f0000 + 20404
33  SimVirtualLocation            	       0x10491c064 0x1048f0000 + 180324
34  SimVirtualLocation            	       0x10491b9d8 0x1048f0000 + 178648
35  libdispatch.dylib             	       0x18fec0750 _dispatch_call_block_and_release + 32
36  libdispatch.dylib             	       0x18fec23e8 _dispatch_client_callout + 20
37  libdispatch.dylib             	       0x18fec58ec _dispatch_continuation_pop + 600
38  libdispatch.dylib             	       0x18fec4f08 _dispatch_async_redirect_invoke + 584
39  libdispatch.dylib             	       0x18fed3ea8 _dispatch_root_queue_drain + 392
40  libdispatch.dylib             	       0x18fed46b8 _dispatch_worker_thread2 + 156
41  libsystem_pthread.dylib       	       0x19006efd0 _pthread_wqthread + 228
42  libsystem_pthread.dylib       	       0x19006dd28 start_wqthread + 8

Thread 5:: WebCore: Scrolling
0   libsystem_kernel.dylib        	       0x1900321f4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x190044b24 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19003ae34 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x190032578 mach_msg + 24
4   CoreFoundation                	       0x190152680 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x190150f44 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x190150434 CFRunLoopRunSpecific + 608
7   CoreFoundation                	       0x1901ce45c CFRunLoopRun + 64
8   JavaScriptCore                	       0x1ac6502cc WTF::Detail::CallableWrapper<WTF::RunLoop::create(char const*, WTF::ThreadType, WTF::Thread::QOS)::$_1, void>::call() + 52
9   JavaScriptCore                	       0x1ac673758 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 244
10  JavaScriptCore                	       0x1ac4b6120 WTF::wtfThreadEntryPoint(void*) + 16
11  libsystem_pthread.dylib       	       0x190072f94 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x19006dd34 thread_start + 8

Thread 6::  Dispatch queue: com.apple.libtrace.state.block-list
0   libsystem_kernel.dylib        	       0x190033fac __ulock_wait + 8
1   libdispatch.dylib             	       0x18fec2dd8 _dlock_wait + 56
2   libdispatch.dylib             	       0x18fec2b8c _dispatch_thread_event_wait_slow + 56
3   libdispatch.dylib             	       0x18fed1bc4 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4   libdispatch.dylib             	       0x18fed1770 _dispatch_sync_f_slow + 148
5   libsystem_trace.dylib         	       0x18fdc8bac ___os_state_request_for_self_block_invoke + 372
6   libdispatch.dylib             	       0x18fec0750 _dispatch_call_block_and_release + 32
7   libdispatch.dylib             	       0x18fec23e8 _dispatch_client_callout + 20
8   libdispatch.dylib             	       0x18fec9a14 _dispatch_lane_serial_drain + 748
9   libdispatch.dylib             	       0x18feca578 _dispatch_lane_invoke + 432
10  libdispatch.dylib             	       0x18fed52d0 _dispatch_root_queue_drain_deferred_wlh + 288
11  libdispatch.dylib             	       0x18fed4b44 _dispatch_workloop_worker_thread + 404
12  libsystem_pthread.dylib       	       0x19006f00c _pthread_wqthread + 288
13  libsystem_pthread.dylib       	       0x19006dd28 start_wqthread + 8

Thread 7:: CVDisplayLink
0   libsystem_kernel.dylib        	       0x1900359ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19007355c _pthread_cond_wait + 1228
2   CoreVideo                     	       0x198b52094 CVDisplayLink::runIOThread() + 732
3   libsystem_pthread.dylib       	       0x190072f94 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x19006dd34 thread_start + 8

Thread 8:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1900321f4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x190044b24 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19003ae34 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x190032578 mach_msg + 24
4   CoreFoundation                	       0x190152680 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x190150f44 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x190150434 CFRunLoopRunSpecific + 608
7   AppKit                        	       0x193ada188 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x190072f94 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x19006dd34 thread_start + 8

Thread 9:
0   libsystem_pthread.dylib       	       0x19006dd20 start_wqthread + 0

Thread 4 crashed with ARM Thread State (64-bit):
    x0: 0x00000000000003d9   x1: 0x00000001b435960f   x2: 0x00000001b43596b7   x3: 0x0000000000000098
    x4: 0x0000000000000002   x5: 0x00000000000013f0   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x000000016b9eb0e0   x9: 0x000000000000f003  x10: 0x01000001f80d9f75  x11: 0x000000000000000e
   x12: 0x000000013fad0258  x13: 0x0000000000000028  x14: 0x000000000000000f  x15: 0x0000000000000000
   x16: 0x000000019006dda4  x17: 0x000000020225ead0  x18: 0x0000000000000000  x19: 0x000000011803c320
   x20: 0x000000011803c320  x21: 0x000000011803c328  x22: 0x000000011803c330  x23: 0x0000000104939000
   x24: 0x0000000104939000  x25: 0x0000000000000001  x26: 0x0000000000000002  x27: 0x0000000000000000
   x28: 0x00006000015bde90   fp: 0x000000016b9e59c0   lr: 0x00000001b3bb37f4
    sp: 0x000000016b9e59a0   pc: 0x00000001b35df888 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf200c471 (Breakpoint) pointer authentication trap IB`

**Comment by nexron171** [comment]
I have uploaded a new build, version 3.5.1. It should be fixed now.
