### ISSUE TITLE
Error: No such option: -8

### ISSUE THREAD

**Issue by TrookyWooky** [nexron171/SimVirtualLocation#7]
<img width="251" alt="image" src="https://github.com/nexron171/SimVirtualLocation/assets/31387964/c7a4b7fe-e89f-4ab2-bf38-4635ccff23ae">

**Comment by nexron171** [comment]
Hi, can you please try with latest version?

**Comment by styresdc** [comment]
Hi @nexron171 not sure if the OP was also on iOS 17 but I encountered the same issue while on the latest version. Taking a look I created a small PR #9 that fixes the problem for me.

**Comment by nexron171** [comment]
Hi! @styresdc fixed it and fix is available in 3.3 https://github.com/nexron171/SimVirtualLocation/releases/tag/3.3
