### ISSUE TITLE
Current location is unavailable

### ISSUE THREAD

**Issue by ThangKoi** [nexron171/SimVirtualLocation#8]
![Screenshot 2023-12-29 124231](https://github.com/nexron171/SimVirtualLocation/assets/3735834/f18f6111-2d39-40e0-bcf0-0d98b0771a5b)

Hi. I use macOS on VMware, and I can't show maps. It show error "Current location is unavailable". Pls help.

**Comment by trongnhan68** [comment]
hello @ThangKoi @cowpatch ,
you can check out the source code and update the method of setCoordinate.
Because this method is only set positive value.

**Comment by nexron171** [comment]
Some times this error can occur in cases when your mac restricts app to obtain mac location. Its not affects app functionality, only initial location on the map
